@apiURL = http://127.0.0.1:8080
### Get the entire hotel
GET {{apiURL}}/hotel
### Get hotel rooms
GET {{apiURL}}/rooms
### create booking
POST {{apiURL}}/bookings
Content-Type: application/json

{
    "room_id":1,
    "guest_id":3,
    "date_from":"2026-04-14",
    "date_to":"2026-04-30"
}